export const buyKeywords = [
  "chốt",
  "chot",
  "mua",
  "lấy",
  "lay",
  "order",
  "đặt",
  "dat",
  "xí",
  "xi",
  "xin giá",
  "xin gia",
  "lên đơn",
  "len don",
  "chốt đơn",
  "chot don",
  "lấy 1",
  "lay 1",
  "lấy 2",
  "lay 2",
  "mua 1",
  "mua 2",
];

export const priceKeywords = [
  "bao nhiêu",
  "bao nhieu",
  "bn",
  "giá",
  "gia",
  "nhiêu tiền",
  "nhieu tien",
  "mấy tiền",
  "may tien",
  "bao tiền",
  "bao tien",
  "giá sao",
  "gia sao",
  "giá nhiêu",
  "gia nhieu",
  "giá bao nhiêu",
  "gia bao nhieu",
  "có mã giảm",
  "co ma giam",
  "voucher",
  "giảm không",
  "giam khong",
];

export const stockKeywords = [
  "còn không",
  "con khong",
  "còn ko",
  "con ko",
  "còn hàng",
  "con hang",
  "còn size",
  "con size",
  "còn màu",
  "con mau",
  "còn mã",
  "con ma",
  "hết chưa",
  "het chua",
];

export const shippingKeywords = [
  "ship",
  "giao",
  "cod",
  "phí ship",
  "phi ship",
  "vận chuyển",
  "van chuyen",
  "miễn ship",
  "mien ship",
  "giao hàng",
  "giao hang",
  "mấy ngày nhận",
  "may ngay nhan",
  "bao lâu nhận",
  "bao lau nhan",
  "hỏa tốc",
  "hoa toc",
  "trong ngày",
  "trong ngay",
  "kiểm tra hàng",
  "kiem tra hang",
  "đổi trả",
  "doi tra",
  "trả hàng",
  "tra hang",
  "không vừa",
  "khong vua",
  "bị lỗi",
  "bi loi",
];

export const productKeywords = [
  "mã",
  "ma",
  "sản phẩm",
  "san pham",
  "kg",
  "cao",
  "nặng",
  "nang",
  "vừa không",
  "vua khong",
  "mặc vừa",
  "mac vua",
  "mặc size",
  "mac size",
  "tư vấn size",
  "tu van size",
  "chất",
  "chat",
  "vải",
  "vai",
  "xù",
  "xu",
  "mát không",
  "mat khong",
  "mua lẻ",
  "mua le",
  "bộ này",
  "bo nay",
  "da dầu",
  "da dau",
  "da khô",
  "da kho",
  "hỗn hợp",
  "hon hop",
  "dùng được cho da",
  "dung duoc cho da",
  // ponytail: vớt QUESTION colloquial — only unambiguous tokens (hop/loa/day/ngan removed: substring of shop/loai/day/ngan)
  "đựng",
  "dung",
  "dây đeo",
  "day deo",
  "sạc",
  "sac",
  "pin",
  "charge",
  "cotton",
  "coton",
];

export const weakProductKeywords = ["size", "sz", "màu", "mau", "trắng", "trang", "đen", "den", "đỏ", "do", "xanh"];

export const howToBuyKeywords = [
  "bấm mua",
  "bam mua",
  "mua thế nào",
  "mua the nao",
  "mua sao",
  "đặt thế nào",
  "dat the nao",
  "đặt hàng sao",
  "dat hang sao",
  "chốt sao",
  "chot sao",
  "làm sao mua",
  "lam sao mua",
  "mua ở đâu",
  "mua o dau",
];

export const spamKeywords = ["telegram", "join telegram", "whatsapp", "zalo nhóm", "zalo nhom", "inbox riêng", "ib riêng"];

export const alreadyOrderedKeywords = [
  "đặt rồi",
  "dat roi",
  "đã đặt",
  "da dat",
  "order rồi",
  "order roi",
  "đã order",
  "da order",
  "chốt rồi",
  "chot roi",
  "đã chốt",
  "da chot",
  "mua rồi",
  "mua roi",
  "đã mua",
  "da mua",
];

export const productDemoKeywords = [
  "mặc thử",
  "mac thu",
  "mặc cho xem",
  "mac cho xem",
  "thử cho xem",
  "thu cho xem",
  "xoay xem",
  "xoay cho xem",
  "demo",
  "trên người",
  "tren nguoi",
  "lên người",
  "len nguoi",
  "mặc lên",
  "mac len",
];

export const topicKeywords: Record<string, string[]> = {
  size: ["size", "sz", "cỡ", "vừa không", "vua khong", "mặc vừa", "mac vua", "tư vấn size", "tu van size", "mặc size", "mac size"],
  size_variant: ["còn size", "con size", "hết size", "het size", "size nào còn", "size nao con"],
  color: [
    "màu",
    "mau",
    "trắng",
    "trang",
    "đen",
    "den",
    "đỏ",
    "do",
    "xanh",
    "vàng",
    "vang",
    "hồng",
    "hong",
    "be",
    "nâu",
    "nau",
    "kem",
    "tím",
    "tim",
    "cam",
    "ghi",
    "xám",
    "xam",
  ],
  material: ["chất", "chat", "vải", "vai", "xù", "xu", "mát không", "mat khong", "chất vải", "chat vai", "thun", "cotton", "lụa", "lua"],
  weight: ["nặng", "nang", "kg", "cân nặng", "can nang", "bao nhiêu kg", "bao nhieu kg"],
  capacity: ["dung tích", "dung tich", "chứa được", "chua duoc", "sức chứa", "suc chua"],
  fee: ["phí ship", "phi ship", "ship bao nhiêu", "ship bao nhieu", "miễn ship", "mien ship", "phí giao", "phi giao"],
  delivery_time: ["mấy ngày", "may ngay", "bao lâu", "bao lau", "khi nào nhận", "khi nao nhan", "hỏa tốc", "hoa toc", "trong ngày", "trong ngay"],
};

// ponytail: "phân vân" — khách đang so sánh/lưỡng lự giữa các lựa chọn (màu/size/mẫu...).
// Đây là tín hiệu mua hàng MẠNH (khách đã quan tâm, chỉ còn thiếu 1 cú đẩy tư vấn) nên cần
// tách riêng khỏi "ask_product" (hỏi sản phẩm chung chung) để seller lọc ra chủ động nhắn.
export const undecidedKeywords = [
  "phân vân",
  "phan van",
  "đắn đo",
  "dan do",
  "lưỡng lự",
  "luong lu",
  "không biết chọn",
  "khong biet chon",
  "chưa biết chọn",
  "chua biet chon",
  "không biết nên",
  "khong biet nen",
  "chưa biết nên",
  "chua biet nen",
  "chọn cái nào",
  "chon cai nao",
  "chọn màu nào",
  "chon mau nao",
  "hay là",
  "hay la",
  "khó chọn quá",
  "kho chon qua",
  "chưa chọn được",
  "chua chon duoc",
  "không chọn được",
  "khong chon duoc",
];

// potentialBuyerIntents đã chuyển sang comment-config.ts (là config điểm/intent, không phải keyword).
export { potentialBuyerIntents } from "./comment-config.js";
